// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fuszerkomat_api.Data;

#nullable disable

namespace fuszerkomat_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251022110356_seed-categories")]
    partial class seedcategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TagWorkTask", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.Property<int>("WorkTasksId")
                        .HasColumnType("int");

                    b.HasKey("TagsId", "WorkTasksId");

                    b.HasIndex("WorkTasksId");

                    b.ToTable("WotkTaskTags", (string)null);
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProfileId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryType = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryType = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryType = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryType = 3
                        },
                        new
                        {
                            Id = 5,
                            CategoryType = 4
                        },
                        new
                        {
                            Id = 6,
                            CategoryType = 5
                        },
                        new
                        {
                            Id = 7,
                            CategoryType = 6
                        },
                        new
                        {
                            Id = 8,
                            CategoryType = 7
                        },
                        new
                        {
                            Id = 9,
                            CategoryType = 8
                        },
                        new
                        {
                            Id = 10,
                            CategoryType = 9
                        },
                        new
                        {
                            Id = 11,
                            CategoryType = 10
                        },
                        new
                        {
                            Id = 12,
                            CategoryType = 11
                        },
                        new
                        {
                            Id = 13,
                            CategoryType = 12
                        },
                        new
                        {
                            Id = 14,
                            CategoryType = 13
                        },
                        new
                        {
                            Id = 15,
                            CategoryType = 14
                        },
                        new
                        {
                            Id = 16,
                            CategoryType = 15
                        });
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.CompanyProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BackgroundImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("CompanyProfiles");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.Opinion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CompanyProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyProfileId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("AuthorUserId", "CompanyId")
                        .IsUnique();

                    b.ToTable("Opinions");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.Realization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProfileId");

                    b.ToTable("Realization");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryType")
                        .HasColumnType("int");

                    b.Property<int>("TagType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryType = 0,
                            TagType = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryType = 0,
                            TagType = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryType = 0,
                            TagType = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryType = 0,
                            TagType = 3
                        },
                        new
                        {
                            Id = 5,
                            CategoryType = 0,
                            TagType = 4
                        },
                        new
                        {
                            Id = 6,
                            CategoryType = 0,
                            TagType = 5
                        },
                        new
                        {
                            Id = 7,
                            CategoryType = 0,
                            TagType = 6
                        },
                        new
                        {
                            Id = 8,
                            CategoryType = 0,
                            TagType = 7
                        },
                        new
                        {
                            Id = 9,
                            CategoryType = 0,
                            TagType = 8
                        },
                        new
                        {
                            Id = 10,
                            CategoryType = 0,
                            TagType = 9
                        },
                        new
                        {
                            Id = 11,
                            CategoryType = 0,
                            TagType = 10
                        },
                        new
                        {
                            Id = 12,
                            CategoryType = 0,
                            TagType = 11
                        },
                        new
                        {
                            Id = 13,
                            CategoryType = 0,
                            TagType = 12
                        },
                        new
                        {
                            Id = 14,
                            CategoryType = 0,
                            TagType = 13
                        },
                        new
                        {
                            Id = 15,
                            CategoryType = 0,
                            TagType = 14
                        },
                        new
                        {
                            Id = 16,
                            CategoryType = 1,
                            TagType = 15
                        },
                        new
                        {
                            Id = 17,
                            CategoryType = 1,
                            TagType = 16
                        },
                        new
                        {
                            Id = 18,
                            CategoryType = 1,
                            TagType = 17
                        },
                        new
                        {
                            Id = 19,
                            CategoryType = 1,
                            TagType = 18
                        },
                        new
                        {
                            Id = 20,
                            CategoryType = 1,
                            TagType = 19
                        },
                        new
                        {
                            Id = 21,
                            CategoryType = 1,
                            TagType = 20
                        },
                        new
                        {
                            Id = 22,
                            CategoryType = 1,
                            TagType = 21
                        },
                        new
                        {
                            Id = 23,
                            CategoryType = 1,
                            TagType = 22
                        },
                        new
                        {
                            Id = 24,
                            CategoryType = 1,
                            TagType = 23
                        },
                        new
                        {
                            Id = 25,
                            CategoryType = 1,
                            TagType = 24
                        },
                        new
                        {
                            Id = 26,
                            CategoryType = 2,
                            TagType = 25
                        },
                        new
                        {
                            Id = 27,
                            CategoryType = 2,
                            TagType = 26
                        },
                        new
                        {
                            Id = 28,
                            CategoryType = 2,
                            TagType = 27
                        },
                        new
                        {
                            Id = 29,
                            CategoryType = 2,
                            TagType = 28
                        },
                        new
                        {
                            Id = 30,
                            CategoryType = 2,
                            TagType = 29
                        },
                        new
                        {
                            Id = 31,
                            CategoryType = 2,
                            TagType = 30
                        },
                        new
                        {
                            Id = 32,
                            CategoryType = 2,
                            TagType = 31
                        },
                        new
                        {
                            Id = 33,
                            CategoryType = 3,
                            TagType = 32
                        },
                        new
                        {
                            Id = 34,
                            CategoryType = 3,
                            TagType = 33
                        },
                        new
                        {
                            Id = 35,
                            CategoryType = 3,
                            TagType = 34
                        },
                        new
                        {
                            Id = 36,
                            CategoryType = 3,
                            TagType = 35
                        },
                        new
                        {
                            Id = 37,
                            CategoryType = 3,
                            TagType = 36
                        },
                        new
                        {
                            Id = 38,
                            CategoryType = 3,
                            TagType = 37
                        },
                        new
                        {
                            Id = 39,
                            CategoryType = 3,
                            TagType = 38
                        },
                        new
                        {
                            Id = 40,
                            CategoryType = 3,
                            TagType = 39
                        },
                        new
                        {
                            Id = 41,
                            CategoryType = 4,
                            TagType = 40
                        },
                        new
                        {
                            Id = 42,
                            CategoryType = 4,
                            TagType = 41
                        },
                        new
                        {
                            Id = 43,
                            CategoryType = 4,
                            TagType = 42
                        },
                        new
                        {
                            Id = 44,
                            CategoryType = 4,
                            TagType = 43
                        },
                        new
                        {
                            Id = 45,
                            CategoryType = 4,
                            TagType = 44
                        },
                        new
                        {
                            Id = 46,
                            CategoryType = 4,
                            TagType = 45
                        },
                        new
                        {
                            Id = 47,
                            CategoryType = 5,
                            TagType = 46
                        },
                        new
                        {
                            Id = 48,
                            CategoryType = 5,
                            TagType = 47
                        },
                        new
                        {
                            Id = 49,
                            CategoryType = 5,
                            TagType = 48
                        },
                        new
                        {
                            Id = 50,
                            CategoryType = 5,
                            TagType = 49
                        },
                        new
                        {
                            Id = 51,
                            CategoryType = 5,
                            TagType = 50
                        },
                        new
                        {
                            Id = 52,
                            CategoryType = 5,
                            TagType = 51
                        },
                        new
                        {
                            Id = 53,
                            CategoryType = 5,
                            TagType = 52
                        },
                        new
                        {
                            Id = 54,
                            CategoryType = 5,
                            TagType = 53
                        },
                        new
                        {
                            Id = 55,
                            CategoryType = 5,
                            TagType = 54
                        },
                        new
                        {
                            Id = 56,
                            CategoryType = 5,
                            TagType = 55
                        },
                        new
                        {
                            Id = 57,
                            CategoryType = 6,
                            TagType = 56
                        },
                        new
                        {
                            Id = 58,
                            CategoryType = 6,
                            TagType = 57
                        },
                        new
                        {
                            Id = 59,
                            CategoryType = 6,
                            TagType = 58
                        },
                        new
                        {
                            Id = 60,
                            CategoryType = 6,
                            TagType = 59
                        },
                        new
                        {
                            Id = 61,
                            CategoryType = 6,
                            TagType = 60
                        },
                        new
                        {
                            Id = 62,
                            CategoryType = 6,
                            TagType = 61
                        },
                        new
                        {
                            Id = 63,
                            CategoryType = 6,
                            TagType = 62
                        },
                        new
                        {
                            Id = 64,
                            CategoryType = 7,
                            TagType = 63
                        },
                        new
                        {
                            Id = 65,
                            CategoryType = 7,
                            TagType = 64
                        },
                        new
                        {
                            Id = 66,
                            CategoryType = 7,
                            TagType = 65
                        },
                        new
                        {
                            Id = 67,
                            CategoryType = 7,
                            TagType = 66
                        },
                        new
                        {
                            Id = 68,
                            CategoryType = 7,
                            TagType = 67
                        },
                        new
                        {
                            Id = 69,
                            CategoryType = 7,
                            TagType = 68
                        },
                        new
                        {
                            Id = 70,
                            CategoryType = 7,
                            TagType = 69
                        },
                        new
                        {
                            Id = 71,
                            CategoryType = 8,
                            TagType = 70
                        },
                        new
                        {
                            Id = 72,
                            CategoryType = 8,
                            TagType = 71
                        },
                        new
                        {
                            Id = 73,
                            CategoryType = 8,
                            TagType = 72
                        },
                        new
                        {
                            Id = 74,
                            CategoryType = 8,
                            TagType = 73
                        },
                        new
                        {
                            Id = 75,
                            CategoryType = 8,
                            TagType = 74
                        },
                        new
                        {
                            Id = 76,
                            CategoryType = 8,
                            TagType = 75
                        },
                        new
                        {
                            Id = 77,
                            CategoryType = 8,
                            TagType = 76
                        },
                        new
                        {
                            Id = 78,
                            CategoryType = 9,
                            TagType = 77
                        },
                        new
                        {
                            Id = 79,
                            CategoryType = 9,
                            TagType = 78
                        },
                        new
                        {
                            Id = 80,
                            CategoryType = 9,
                            TagType = 79
                        },
                        new
                        {
                            Id = 81,
                            CategoryType = 9,
                            TagType = 80
                        },
                        new
                        {
                            Id = 82,
                            CategoryType = 9,
                            TagType = 81
                        },
                        new
                        {
                            Id = 83,
                            CategoryType = 9,
                            TagType = 82
                        },
                        new
                        {
                            Id = 84,
                            CategoryType = 9,
                            TagType = 83
                        },
                        new
                        {
                            Id = 85,
                            CategoryType = 9,
                            TagType = 84
                        },
                        new
                        {
                            Id = 86,
                            CategoryType = 10,
                            TagType = 85
                        },
                        new
                        {
                            Id = 87,
                            CategoryType = 10,
                            TagType = 86
                        },
                        new
                        {
                            Id = 88,
                            CategoryType = 10,
                            TagType = 87
                        },
                        new
                        {
                            Id = 89,
                            CategoryType = 10,
                            TagType = 88
                        },
                        new
                        {
                            Id = 90,
                            CategoryType = 10,
                            TagType = 89
                        },
                        new
                        {
                            Id = 91,
                            CategoryType = 10,
                            TagType = 90
                        },
                        new
                        {
                            Id = 92,
                            CategoryType = 10,
                            TagType = 91
                        },
                        new
                        {
                            Id = 93,
                            CategoryType = 10,
                            TagType = 92
                        },
                        new
                        {
                            Id = 94,
                            CategoryType = 10,
                            TagType = 93
                        },
                        new
                        {
                            Id = 95,
                            CategoryType = 11,
                            TagType = 94
                        },
                        new
                        {
                            Id = 96,
                            CategoryType = 11,
                            TagType = 95
                        },
                        new
                        {
                            Id = 97,
                            CategoryType = 11,
                            TagType = 96
                        },
                        new
                        {
                            Id = 98,
                            CategoryType = 11,
                            TagType = 97
                        },
                        new
                        {
                            Id = 99,
                            CategoryType = 11,
                            TagType = 98
                        },
                        new
                        {
                            Id = 100,
                            CategoryType = 11,
                            TagType = 99
                        },
                        new
                        {
                            Id = 101,
                            CategoryType = 11,
                            TagType = 100
                        },
                        new
                        {
                            Id = 102,
                            CategoryType = 12,
                            TagType = 101
                        },
                        new
                        {
                            Id = 103,
                            CategoryType = 12,
                            TagType = 102
                        },
                        new
                        {
                            Id = 104,
                            CategoryType = 12,
                            TagType = 103
                        },
                        new
                        {
                            Id = 105,
                            CategoryType = 12,
                            TagType = 104
                        },
                        new
                        {
                            Id = 106,
                            CategoryType = 12,
                            TagType = 105
                        },
                        new
                        {
                            Id = 107,
                            CategoryType = 12,
                            TagType = 106
                        },
                        new
                        {
                            Id = 108,
                            CategoryType = 13,
                            TagType = 107
                        },
                        new
                        {
                            Id = 109,
                            CategoryType = 13,
                            TagType = 108
                        },
                        new
                        {
                            Id = 110,
                            CategoryType = 13,
                            TagType = 109
                        },
                        new
                        {
                            Id = 111,
                            CategoryType = 13,
                            TagType = 110
                        },
                        new
                        {
                            Id = 112,
                            CategoryType = 13,
                            TagType = 111
                        },
                        new
                        {
                            Id = 113,
                            CategoryType = 13,
                            TagType = 112
                        },
                        new
                        {
                            Id = 114,
                            CategoryType = 13,
                            TagType = 113
                        },
                        new
                        {
                            Id = 115,
                            CategoryType = 14,
                            TagType = 114
                        },
                        new
                        {
                            Id = 116,
                            CategoryType = 14,
                            TagType = 115
                        },
                        new
                        {
                            Id = 117,
                            CategoryType = 14,
                            TagType = 116
                        },
                        new
                        {
                            Id = 118,
                            CategoryType = 14,
                            TagType = 117
                        },
                        new
                        {
                            Id = 119,
                            CategoryType = 14,
                            TagType = 118
                        },
                        new
                        {
                            Id = 120,
                            CategoryType = 14,
                            TagType = 119
                        },
                        new
                        {
                            Id = 121,
                            CategoryType = 14,
                            TagType = 120
                        },
                        new
                        {
                            Id = 122,
                            CategoryType = 15,
                            TagType = 121
                        });
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.TaskApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WorkTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyUserId");

                    b.HasIndex("WorkTaskId", "CompanyUserId")
                        .IsUnique();

                    b.ToTable("TaskApplications");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.Token.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.WorkTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpectedRealisationTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("WorkTasks");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.WorkTaskGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkTaskId");

                    b.ToTable("WorkTaskGalleries");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("fuszerkomat_api.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("fuszerkomat_api.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fuszerkomat_api.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("fuszerkomat_api.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagWorkTask", b =>
                {
                    b.HasOne("fuszerkomat_api.Data.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fuszerkomat_api.Data.Models.WorkTask", null)
                        .WithMany()
                        .HasForeignKey("WorkTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.Address", b =>
                {
                    b.HasOne("fuszerkomat_api.Data.Models.CompanyProfile", "CompanyProfile")
                        .WithOne("Address")
                        .HasForeignKey("fuszerkomat_api.Data.Models.Address", "CompanyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyProfile");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.CompanyProfile", b =>
                {
                    b.HasOne("fuszerkomat_api.Data.Models.AppUser", "AppUser")
                        .WithOne("CompanyProfile")
                        .HasForeignKey("fuszerkomat_api.Data.Models.CompanyProfile", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.Opinion", b =>
                {
                    b.HasOne("fuszerkomat_api.Data.Models.AppUser", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("fuszerkomat_api.Data.Models.AppUser", "CompanyUser")
                        .WithMany("Opinions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("fuszerkomat_api.Data.Models.CompanyProfile", null)
                        .WithMany("Opinions")
                        .HasForeignKey("CompanyProfileId");

                    b.HasOne("fuszerkomat_api.Data.Models.UserProfile", null)
                        .WithMany("OpinionsAuthored")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("AuthorUser");

                    b.Navigation("CompanyUser");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.Realization", b =>
                {
                    b.HasOne("fuszerkomat_api.Data.Models.CompanyProfile", "CompanyProfile")
                        .WithMany("Realizations")
                        .HasForeignKey("CompanyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyProfile");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.TaskApplication", b =>
                {
                    b.HasOne("fuszerkomat_api.Data.Models.AppUser", "CompanyUser")
                        .WithMany("CompanyApplications")
                        .HasForeignKey("CompanyUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("fuszerkomat_api.Data.Models.WorkTask", "WorkTask")
                        .WithMany("Applications")
                        .HasForeignKey("WorkTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyUser");

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.Token.RefreshToken", b =>
                {
                    b.HasOne("fuszerkomat_api.Data.Models.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.UserProfile", b =>
                {
                    b.HasOne("fuszerkomat_api.Data.Models.AppUser", "AppUser")
                        .WithOne("UserProfile")
                        .HasForeignKey("fuszerkomat_api.Data.Models.UserProfile", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.WorkTask", b =>
                {
                    b.HasOne("fuszerkomat_api.Data.Models.Category", "Category")
                        .WithMany("WorkTasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("fuszerkomat_api.Data.Models.AppUser", "CreatedByUser")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.WorkTaskGallery", b =>
                {
                    b.HasOne("fuszerkomat_api.Data.Models.WorkTask", "WorkTask")
                        .WithMany("Images")
                        .HasForeignKey("WorkTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.AppUser", b =>
                {
                    b.Navigation("CompanyApplications");

                    b.Navigation("CompanyProfile");

                    b.Navigation("CreatedTasks");

                    b.Navigation("Opinions");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.Category", b =>
                {
                    b.Navigation("WorkTasks");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.CompanyProfile", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Opinions");

                    b.Navigation("Realizations");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.UserProfile", b =>
                {
                    b.Navigation("OpinionsAuthored");
                });

            modelBuilder.Entity("fuszerkomat_api.Data.Models.WorkTask", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
